# Generated by Django 2.2 on 2024-11-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20241120_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
